--Print day of the week of Independence Day
SELECT TO_CHAR(TO_DATE('08/15/1947','MM/DD/YYYY'),'dAy') from DUAL;

SELECT ENAME,SAL,DENSE_RANK() OVER(ORDER BY SAL DESC) AS SRNK
FROM EMP; 

--Query if salary is same sort by hiredate asc

SELECT ENAME,SAL,HIREDATE,DENSE_RANK()OVER(ORDER BY SAL DESC,HIREDATE ASC) AS RNK
FROM EMP;

--PARTITION BY
BREAK ON DEPTNO SKIP 5
SELECT deptno,ENAME,SAL,HIREDATE, DENSE_Rank()OVER(PARTITION BY DEPTNO ORDER BY SAL DESC) FROM EMP;

--Display nth highest
select * from (SELECT ENAME,sal,DENSE_RANK()OVER(ORDER BY SAL DESC) AS RNK from emp) e
where rnk=2

--Display nth highest in dept no 10

select * FROM (SELECT empno,ename,sal,deptno, DENSE_RANK()OVER(PARTITION BY DEPTNO ORDER BY SAL DESC) AS RNK  FROM EMP WHERE DEPTNO = 10) ASK
WHERE RNK = &N;

--First five rows

SELECT * FROM EMP
ORDER BY SAL DESC 
FETCH FIRST 5 ROWS ONLY;

--Fetch query from 6th-10th

SELECT * FROM EMP
ORDER BY SAL DESC 
OFFSET 4 ROWS
FETCH NEXT 4 ROWS ONLY;

--iT GIVES A ROWNUMBER RETURNS RECORD NUMBER AFTER SORTING
SELECT ROW_NUMBER() OVER (ORDER BY SAL DESC)AS RNO,EMPNO,SAL
FROM EMP 
ORDER BY SAL DESC

--Job-wise number of employees

select COUNT(*),JOB 
FROM EMP
GROUP BY JOB
ORDER BY 1 DESC

-- Display total employees joined in 1981
SELECT * FROM (
SELECT TO_CHAR(HIREDATE,'YYYY')as yr,count(*)
from emp 
group by TO_CHAR(HIREDATE,'YYYY')) yr
where yr BETWEEN 1980 AND 1990

SELECT COUNT(*),TO_CHAR(HIREDATE,'YYYY') AS YEAROFJOINING
FROM EMP
WHERE TO_CHAR(HIREDATE,'YYYY')=1981
GROUP BY TO_CHAR(HIREDATE,'YYYY')
--deptno in 10,20 and sum(sal)>10000
SELECT SUM(SAL),DEPTNO
FROM EMP
WHERE DEPTNO IN (10,20)
GROUP BY DEPTNO
HAVING SUM(SAL)>10000
ORDER BY 1 DESC
--year wise quarter wise sum of employees
SELECT TO_CHAR(HIREDATE,'YYYY') as year,TO_CHAR(HIREDATE,'Q')as quarter,count(*) as employees
FROM EMP
GROUP BY TO_CHAR(HIREDATE,'YYYY'),TO_CHAR(HIREDATE,'Q')
ORDER BY 1,2;

--DeptWise job 

SELECT JOB, DEPTNO,sum(sal) 
FROM EMP
GROUP BY ROLLUP(DEPTNO,JOB)
ORDER BY DEPTNO

--Grand Total

SELECT JOB, DEPTNO,sum(sal) 
FROM EMP
GROUP BY CUBE(DEPTNO,JOB)
ORDER BY DEPTNO

--Query for yearwise and quarter wise subtotals
SELECT TO_CHAR(HIREDATE,'YYYY'),TO_CHAR(HIREDATE,'Q'),SUM(SAL)
FROM EMP
GROUP BY ROLLUP(TO_CHAR(HIREDATE,'YYYY'),TO_CHAR(HIREDATE,'Q'))
