version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      - POSTGRES_USER=mahesh
      - POSTGRES_PASSWORD=mahesh
      - POSTGRES_DB=college_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8081:80"  # Changed from 8080 to 8081
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
