--Emp,Salgrade,dept

SELECT E.ENAME,D.DNAME,S.GRADE
FROM EMP E JOIN DEPT D
ON E.DEPTNO=D.DEPTNO
JOIN SALGRADE S
ON E.SAL BETWEEN S.LOSAL AND S.HISAL;
-----

set autotrace on explain

===
--Employees with same manager
SELECT E1.ENAME AS ENAME,E2.ENAME As manager
FROM EMP E1,EMP E2
WHERE E1.MGR = E2.EMPNO


--Employees reportin to blake

SELECT E1.ENAME AS EMPLOYEES, E2.ENAME AS MANAGER
FROM EMP E1, EMP E2
WHERE E1.MGR = E2.EMPNO
AND E2.ENAME = 'BLAKE'

----

SELECT * FROM EMP;
--Display employees who earn more than their manager

SELECT E1.ENAME AS EMPLOYEENAME,E1.SAL AS EMPLOYEESALARY,E2.ENAME AS MANAGERNAME,E2.SAL AS MANAGERSAL
FROM EMP E1,EMP E2
WHERE E1.MGR=E2.EMPNO
AND E1.SAL>E2.SAL

select * from emp
-Display employees who joined before their managers
SELECT E1.ENAME AS EMPLOYEENAME,E1.HIREDATE AS EMPLOYEEHIREDATE, E2.ENAME AS MANAGER,E2.HIREDATE AS MANAGERHIREDATE
FROM EMP E1,EMP E2
WHERE E1.MGR = E2.EMPNO
AND TO_NUMBER(SYSDATE-E1.HIREDATE)>TO_NUMBER(SYSDATE-E2.HIREDATE)


--Display salgrade,deptname,empno,ename, who report to the same manager

SELECT E1.ENAME AS EMPLOYEENAME,E2.ENAME AS MANAGERNAME,S.GRADE,D.DNAME
FROM EMP E1 JOIN DEPT D 
ON E1.DEPTNO = D.DEPTNO
JOIN SALGRADE S
ON E1.SAL BETWEEN S.LOSAL AND S.HISAL
JOIN EMP E2
ON E1.MGR=E2.EMPNO;
