REM INSERTING into COUNTRIES
SET DEFINE OFF;
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Afghanistan','AF');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Albania','AL');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Algeria','DZ');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('American Samoa','AS');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Andorra','AD');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Angola','AO');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Anguilla','AI');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Antarctica','AQ');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Antigua and Barbuda','AG');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Argentina','AR');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Armenia','AM');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Aruba','AW');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Australia','AU');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Austria','AT');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Azerbaijan','AZ');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Bahamas (the)','BS');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Bahrain','BH');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Bangladesh','BD');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Barbados','BB');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Belarus','BY');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Belgium','BE');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Belize','BZ');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Benin','BJ');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Bermuda','BM');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Bhutan','BT');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Bolivia (Plurinational State of)','BO');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Bonaire, Sint Eustatius and Saba','BQ');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Bosnia and Herzegovina','BA');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Botswana','BW');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Bouvet Island','BV');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Brazil','BR');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('British Indian Ocean Territory (the)','IO');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Brunei Darussalam','BN');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Bulgaria','BG');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Burkina Faso','BF');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Burundi','BI');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Cabo Verde','CV');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Cambodia','KH');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Cameroon','CM');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Canada','CA');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Cayman Islands (the)','KY');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Central African Republic (the)','CF');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Chad','TD');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Chile','CL');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('China','CN');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Christmas Island','CX');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Cocos (Keeling) Islands (the)','CC');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Colombia','CO');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Comoros (the)','KM');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Congo (the Democratic Republic of the)','CD');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Congo (the)','CG');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Cook Islands (the)','CK');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Costa Rica','CR');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Croatia','HR');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Cuba','CU');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Curaçao','CW');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Cyprus','CY');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Czechia','CZ');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Côte d''Ivoire','CI');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Denmark','DK');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Djibouti','DJ');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Dominica','DM');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Dominican Republic (the)','DO');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Ecuador','EC');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Egypt','EG');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('El Salvador','SV');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Equatorial Guinea','GQ');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Eritrea','ER');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Estonia','EE');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Eswatini','SZ');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Ethiopia','ET');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Falkland Islands (the) [Malvinas]','FK');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Faroe Islands (the)','FO');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Fiji','FJ');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Finland','FI');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('France','FR');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('French Guiana','GF');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('French Polynesia','PF');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('French Southern Territories (the)','TF');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Gabon','GA');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Gambia (the)','GM');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Georgia','GE');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Germany','DE');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Ghana','GH');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Gibraltar','GI');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Greece','GR');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Greenland','GL');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Grenada','GD');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Guadeloupe','GP');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Guam','GU');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Guatemala','GT');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Guernsey','GG');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Guinea','GN');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Guinea-Bissau','GW');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Guyana','GY');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Haiti','HT');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Heard Island and McDonald Islands','HM');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Holy See (the)','VA');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Honduras','HN');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Hong Kong','HK');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Hungary','HU');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Iceland','IS');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('India','IN');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Indonesia','ID');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Iran (Islamic Republic of)','IR');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Iraq','IQ');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Ireland','IE');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Isle of Man','IM');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Israel','IL');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Italy','IT');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Jamaica','JM');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Japan','JP');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Jersey','JE');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Jordan','JO');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Kazakhstan','KZ');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Kenya','KE');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Kiribati','KI');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Korea (the Democratic People''s Republic of)','KP');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Korea (the Republic of)','KR');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Kuwait','KW');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Kyrgyzstan','KG');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Lao People''s Democratic Republic (the)','LA');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Latvia','LV');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Lebanon','LB');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Lesotho','LS');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Liberia','LR');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Libya','LY');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Liechtenstein','LI');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Lithuania','LT');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Luxembourg','LU');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Macao','MO');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Madagascar','MG');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Malawi','MW');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Malaysia','MY');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Maldives','MV');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Mali','ML');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Malta','MT');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Marshall Islands (the)','MH');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Martinique','MQ');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Mauritania','MR');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Mauritius','MU');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Mayotte','YT');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Mexico','MX');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Micronesia (Federated States of)','FM');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Moldova (the Republic of)','MD');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Monaco','MC');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Mongolia','MN');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Montenegro','ME');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Montserrat','MS');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Morocco','MA');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Mozambique','MZ');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Myanmar','MM');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Namibia','NA');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Nauru','NR');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Nepal','NP');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Netherlands (the)','NL');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('New Caledonia','NC');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('New Zealand','NZ');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Nicaragua','NI');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Niger (the)','NE');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Nigeria','NG');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Niue','NU');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Norfolk Island','NF');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Northern Mariana Islands (the)','MP');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Norway','NO');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Oman','OM');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Pakistan','PK');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Palau','PW');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Palestine, State of','PS');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Panama','PA');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Papua New Guinea','PG');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Paraguay','PY');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Peru','PE');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Philippines (the)','PH');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Pitcairn','PN');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Poland','PL');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Portugal','PT');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Puerto Rico','PR');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Qatar','QA');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Republic of North Macedonia','MK');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Romania','RO');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Russian Federation (the)','RU');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Rwanda','RW');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Réunion','RE');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Saint Barthélemy','BL');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Saint Helena, Ascension and Tristan da Cunha','SH');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Saint Kitts and Nevis','KN');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Saint Lucia','LC');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Saint Martin (French part)','MF');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Saint Pierre and Miquelon','PM');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Saint Vincent and the Grenadines','VC');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Samoa','WS');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('San Marino','SM');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Sao Tome and Principe','ST');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Saudi Arabia','SA');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Senegal','SN');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Serbia','RS');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Seychelles','SC');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Sierra Leone','SL');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Singapore','SG');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Sint Maarten (Dutch part)','SX');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Slovakia','SK');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Slovenia','SI');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Solomon Islands','SB');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Somalia','SO');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('South Africa','ZA');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('South Georgia and the South Sandwich Islands','GS');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('South Sudan','SS');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Spain','ES');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Sri Lanka','LK');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Sudan (the)','SD');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Suriname','SR');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Svalbard and Jan Mayen','SJ');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Sweden','SE');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Switzerland','CH');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Syrian Arab Republic','SY');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Taiwan (Province of China)','TW');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Tajikistan','TJ');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Tanzania, United Republic of','TZ');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Thailand','TH');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Timor-Leste','TL');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Togo','TG');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Tokelau','TK');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Tonga','TO');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Trinidad and Tobago','TT');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Tunisia','TN');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Turkey','TR');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Turkmenistan','TM');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Turks and Caicos Islands (the)','TC');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Tuvalu','TV');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Uganda','UG');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Ukraine','UA');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('United Arab Emirates (the)','AE');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('United Kingdom of Great Britain and Northern Ireland (the)','GB');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('United States Minor Outlying Islands (the)','UM');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('United States of America (the)','US');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Uruguay','UY');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Uzbekistan','UZ');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Vanuatu','VU');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Venezuela (Bolivarian Republic of)','VE');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Viet Nam','VN');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Virgin Islands (British)','VG');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Virgin Islands (U.S.)','VI');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Wallis and Futuna','WF');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Western Sahara','EH');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Yemen','YE');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Zambia','ZM');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Zimbabwe','ZW');
Insert into COUNTRIES (COUNTRY,COUNTRYCODE) values ('Åland Islands','AX');
